#!/bin/bash

################################################################################
# Daily MCP Backup Setup Script
#
# Sets up automatic daily backups of .claude.json configuration
# Keeps last 7 days of backups in the backups/ directory
#
# Usage:
#   ./setup_daily_backup.sh          # Install cron job
#   ./setup_daily_backup.sh --remove # Remove cron job
################################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP_DIR="$SCRIPT_DIR/backups"
CRON_COMMAND="0 3 * * * $SCRIPT_DIR/backup_claude.sh >> $SCRIPT_DIR/backup.log 2>&1"
CRON_COMMENT="# MCP Daily Backup - Auto-generated by setup_daily_backup.sh"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "=================================="
echo "   MCP Daily Backup Setup"
echo "=================================="
echo ""

# Remove mode
if [ "$1" == "--remove" ]; then
    echo -e "${BLUE}Removing MCP backup cron job...${NC}"

    # Remove the cron job
    crontab -l 2>/dev/null | grep -v "backup_claude.sh" | crontab -

    echo -e "${GREEN}✓ Cron job removed${NC}"
    echo ""
    echo "To reinstall: ./setup_daily_backup.sh"
    exit 0
fi

# Create backups directory if it doesn't exist
if [ ! -d "$BACKUP_DIR" ]; then
    echo -e "${BLUE}Creating backups directory...${NC}"
    mkdir -p "$BACKUP_DIR"
    echo -e "${GREEN}✓ Created: $BACKUP_DIR${NC}"
fi

# Create backup script if it doesn't exist
if [ ! -f "$SCRIPT_DIR/backup_claude.sh" ]; then
    echo -e "${BLUE}Creating backup script...${NC}"

    cat > "$SCRIPT_DIR/backup_claude.sh" << 'BACKUP_SCRIPT'
#!/bin/bash

# Daily MCP Configuration Backup Script
# Called by cron job at 3 AM daily

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP_DIR="$SCRIPT_DIR/backups"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="$BACKUP_DIR/claude_${TIMESTAMP}.json"

# Create backup directory if missing
mkdir -p "$BACKUP_DIR"

# Backup current configuration
if [ -f ~/.claude.json ]; then
    cp ~/.claude.json "$BACKUP_FILE"
    echo "[$(date)] Backed up to: $BACKUP_FILE"

    # Keep only last 7 days of backups
    cd "$BACKUP_DIR"
    ls -t claude_*.json | tail -n +8 | xargs -r rm
    echo "[$(date)] Cleaned old backups, kept last 7"
else
    echo "[$(date)] ERROR: ~/.claude.json not found"
    exit 1
fi
BACKUP_SCRIPT

    chmod +x "$SCRIPT_DIR/backup_claude.sh"
    echo -e "${GREEN}✓ Created: backup_claude.sh${NC}"
fi

# Check if cron job already exists
if crontab -l 2>/dev/null | grep -q "backup_claude.sh"; then
    echo -e "${YELLOW}⚠ Cron job already exists${NC}"
    echo ""
    echo "Existing cron entry:"
    crontab -l | grep "backup_claude.sh"
    echo ""
    read -p "Replace existing cron job? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Cancelled."
        exit 0
    fi

    # Remove old entry
    crontab -l | grep -v "backup_claude.sh" | crontab -
fi

# Add cron job
echo -e "${BLUE}Installing cron job...${NC}"
(crontab -l 2>/dev/null; echo "$CRON_COMMENT"; echo "$CRON_COMMAND") | crontab -

echo -e "${GREEN}✓ Cron job installed${NC}"
echo ""
echo "=================================="
echo "   Setup Complete"
echo "=================================="
echo ""
echo "Schedule: Daily at 3:00 AM"
echo "Backups:  $BACKUP_DIR"
echo "Logs:     $SCRIPT_DIR/backup.log"
echo "Retention: Last 7 days"
echo ""
echo "Commands:"
echo "  View cron:        crontab -l"
echo "  Manual backup:    ./backup_claude.sh"
echo "  Remove cron:      ./setup_daily_backup.sh --remove"
echo "  List backups:     ls -lt backups/"
echo ""
echo "Next backup: Tomorrow at 3:00 AM"
echo ""

# Test backup immediately
echo -e "${BLUE}Running test backup now...${NC}"
"$SCRIPT_DIR/backup_claude.sh"
echo ""

if [ -f "$BACKUP_DIR/$(ls -t $BACKUP_DIR/claude_*.json 2>/dev/null | head -1)" ]; then
    echo -e "${GREEN}✓ Test backup successful${NC}"
    echo ""
    echo "Latest backup:"
    ls -lh "$BACKUP_DIR/"claude_*.json | head -1
else
    echo -e "${RED}✗ Test backup failed${NC}"
    exit 1
fi
